# Generated by Django 3.2 on 2021-05-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
