# Generated by Django 3.2 on 2021-05-14 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0003_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, default=None, related_name='courses_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
